

# Site Settings
title: 						"PAF Docs"
email: 						"demon.devin@gmail.com"
description: 				"A collection of help files focused on the development of portable applications using the PortableApps.com Format"
baseurl: 					""
url: 						"https://demondevin.github.io/pal-docs/"
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"demon.devin"
author_url: 				"http://softables.tk/"
author_bio: 				"A creative virtuoso who seeks an environment which believes the same ideology of a hacker—a true hacker; not a cracker. For hackers will develop, build, and improve a person, place, and/or anything. As for crackers will deface, break, and intrude on a person, place, and/or anything."
author_email: 				"demon.devin@gmail.com"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com"
facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com"
youtube_url:  				"http://youtube.com"
dribbble_url:  				"http://dribbble.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"ecko"
theme_google_comments: 		false
theme_analytics_id: 		"UA-47473884-1"
theme_analytics_domain: 	"ecko.me"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

